services:
  - type: web
    name: crm-in-houston
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - requirements.txt
    autoDeploy: true
